// <auto-generated />
namespace Monopy.PreceRateWage.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class month : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(month));
        
        string IMigrationMetadata.Id
        {
            get { return "201805121221001_month"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
